enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const weapon_book = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, tiles.util.arrow0, function (sprite, location) {
    tiles.loadMap(tiles.createMap(tilemap`level2`))
    tiles.placeOnTile(mySprite, tiles.getTileLocation(2, 15))
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f a a a a f f . . . . 
        . . . f a a a f f a a a f . . . 
        . . f f f f f c c f f f f f . . 
        . . f f a c a c c a c a f f . . 
        . . f a c f c f f c f c a f . . 
        . . f f f c c a a c c f f f . . 
        . f f a f c f a a f c f a f f . 
        . f a a f f a a a a f a a a f . 
        . . f a a a a a a a a a a f . . 
        . . . f a a a a a a a a f . . . 
        . . a 2 f f f f f f f f 2 a . . 
        . . 2 d f c c c c c c f d 2 . . 
        . . 2 2 f 2 2 2 2 2 2 f 2 2 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . f f a a a a f f . . . . . 
        . . f a a a f f a a a f . . . . 
        . . f f f f c c f f f f . . . . 
        . f f a c a c c a c a f f . . . 
        . f a c f c f f f c f a f . . . 
        . f f f c f a a c c f f f . . . 
        . f a c f f a a c f a a f . . . 
        f f a f f a a a f a a a f f . . 
        f f a a a a a a a a a a f a f . 
        . . f a a a a a a a a f f b f . 
        . . a f f f f f f f f c f b f . 
        . . c f c c c c c a d d f c f . 
        . . a f f f f f f a a c f f . . 
        . . . f f f . . . . . . . . . . 
        `,img`
        . . . . . f f f f . . . . . . . 
        . . . f f a a a a f f . . . . . 
        . . f a a a f f a a a f . . . . 
        . f f f f f c c f f f f f . . . 
        . f f a c a c c a c a f f . . . 
        . f a c f c f f c f c a f . . . 
        . f f f c c a a c c f f f . . . 
        f f a f c f a a f c f a f f . . 
        f a a f f a a a a f a a a f . . 
        . f a a a a a a a a a a f . . . 
        . . f a a a a a a a a f . . . . 
        . a 2 f f f f f f f f 2 a . . . 
        . 2 d f c c c c c c f d 2 . . . 
        . 2 2 f 2 2 2 2 2 2 f 2 2 . . . 
        . . . . f f f f f f . . . . . . 
        . . . . f f . . f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . f f a a a a f f . . . . . 
        . . f a a a f f a a a f . . . . 
        . . f f f f c c f f f f . . . . 
        . f f a c a c c a c a f f . . . 
        . f a f c f f f c f c a f . . . 
        . f f f c c a a f c f f f . . . 
        . f a a f c a a f f c a f . . . 
        . f a a a f a a a f f a f f . . 
        . f a a a a a a a a a a f f . . 
        . f f a a a a a a a a f . . . . 
        . f 2 f f f f f f f f a . . . . 
        . f d d a c c c c c f 2 . . . . 
        . f 2 a a f f f f f f a . . . . 
        . . . . . . . . f f f . . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (direction == 1) {
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            ....ffffff..............
            ..ffaaaafcf.............
            .ffaaaafcccf............
            .faaaffaaaaf...cc.......
            .ffffaaccccaf.c2c.......
            .facccffffacfc22c.......
            fffffffaaaffc22c........
            ffa22abf22ac22c.........
            faa2d21fddac2c..........
            .faaa2dddadccc..........
            ..ffaa22a2dda...........
            ...f22cc22aa............
            ...fcc22acf.............
            ...f22cc22f.............
            ....ffffff..............
            .....fff................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            .......fff..............
            ....fffffcf.............
            ..ffaaaaaccff...........
            .ffaaaaaacccff..........
            .faaaafffaaaaf..........
            .fffffaaaccccaf.........
            fffacccfffffacf.........
            fffffffffaaafff.....cc..
            fafa22abbf22aaf...cc2c..
            .faa2d2bbfddaf..cc22cc..
            ..faaa2dddddfaac222c....
            ...fcccccccaaddc2cc.....
            ...f22222ca22ddccc......
            ...ffffffffaaaa.........
            ...fff...ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            .......ff...............
            ....ffffcff.............
            ..ffaaaafcff............
            .ffaaaaafccff...........
            .faaaaffaaaaf...........
            .fffffaaccccaf..........
            fffacccffffacf..........
            ffffffffaaafff..........
            fafa22abf22aaf..........
            .faa2d2bfddaf...........
            ..faaa2dddaa.c..........
            ...fccccaaddaccccccc....
            ...f222a22ddac22222.....
            ...fffffaaaa.ccccc......
            ..ffffffff...c..........
            ..fff..ff...............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ....ffffff..............
            ..ffaaaafcf.............
            .ffaaaafcccf............
            .faaaffaaaaf............
            .ffffaaccccaf...........
            .facccffffacf...........
            fffffffaaafff...........
            ffa22abf22aaf...........
            faa2d21fddaf............
            .faaa2ddddf.............
            ..fdda222af.............
            ..fddaccccc.............
            ...aafccc2c.............
            ...f2222c22c............
            ....fffffc22c...........
            .....fff..c22c..........
            ...........c2c..........
            ............cc..........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (direction == 2) {
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            ..............ffffff....
            .............fcfaaaaff..
            ............fcccfaaaaff.
            .......cc...faaaaffaaaf.
            .......c2c.fcccccaaffff.
            .......c22cfcaffffcccaf.
            ........c22cffaaafffffff
            .........c22ca22fba22aff
            ..........c2caddf12d2aaf
            ..........cccdaddd2aaaf.
            ...........add2a22aaff..
            ............aa22cc22f...
            .............fca22ccf...
            .............f22cc22f...
            ..............ffffff....
            ................fff.....
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ..............fff.......
            .............fcfffff....
            ...........ffccaaaaaff..
            ..........ffcccaaaaaaff.
            ..........faaaafffaaaaf.
            .........faccccaaafffff.
            .........fcafffffcccafff
            ..cc.....fffaaafffffffff
            ..c2cc...faa22fbba22afaf
            ..cc22cc..faddfbb2d2aaf.
            ....c222caafddddd2aaaf..
            .....cc2cddaacccccccf...
            ......cccdd22ac22222f...
            .........aaaaffffffff...
            .............ff...fff...
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ...............ff.......
            .............ffcffff....
            ............ffcfaaaaff..
            ...........ffccfaaaaaff.
            ...........faaaaffaaaaf.
            ..........faccccaafffff.
            ..........fcaffffcccafff
            ..........fffaaaffffffff
            ..........faa22fba22afaf
            ...........faddfb2d2aaf.
            ..........c.aaddd2aaaf..
            ....cccccccaddaaccccf...
            .....22222cadd22a222f...
            ......ccccc.aaaafffff...
            ..........c...ffffffff..
            ...............ff..fff..
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ..............ffffff....
            .............fcfaaaaff..
            ............fcccfaaaaff.
            ............faaaaffaaaf.
            ...........faccccaaffff.
            ...........fcaffffcccaf.
            ...........fffaaafffffff
            ...........faa22fba22aff
            ............faddf12d2aaf
            .............fdddd2aaaf.
            .............fa222addf..
            .............cccccaddf..
            .............c2cccfaa...
            ............c22c2222f...
            ...........c22cfffff....
            ..........c22c..fff.....
            ..........c2c...........
            ..........cc............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (direction == 3) {
        animation.runImageAnimation(
        mySprite,
        [img`
            ..........ffff...........
            ........ffaaaaff.........
            .......faaaffaaaf........
            ......fffffccfffff.......
            ......ffacaccacaff.......
            bbb...facfcffcfcaf.......
            b22b..fffccaaccfff.......
            b222bffafcfaafcfaff......
            .b222baaffaaaafaaaf......
            ..b222baaaaaaaaaaf.......
            ...b222baaaaaaaaf........
            ....b2abffffffff2a.......
            .....bbdfccccccfd2.......
            ......22f222222f22.......
            .........ffffff..........
            .........ff..ff..........
            `,img`
            .........................
            ..........ffff...........
            ........ffaaaaff.........
            .......faaaffaaaf........
            .......ffffccffff........
            ......ffacaccacaff.......
            ......facfcfffcfaf.......
            ......fffcfaaccfff.......
            ......facffaacfaaf.......
            .....ffaffaaafaaaff......
            .....ffaaaaaaaaaafaf.....
            .......faaaaaaaaffbf.....
            .......affffffffcfbf.....
            .......cfcccccaddfcf.....
            .......affffffaacff......
            ........fff..............
            `,img`
            ...........ffff..........
            .........ffaaaaff........
            ........faaaffaaaf.......
            .......fffffccfffff......
            .......ffacaccacaff......
            .......facfcffcfcaf...bbb
            .......fffccaaccfff..b22b
            ......ffafcfaafcfaffb222b
            ......faaafaaaaffaab222b.
            .......faaaaaaaaaab222b..
            ........faaaaaaaab222b...
            .......a2ffffffffba2b....
            .......2dfccccccfdbb.....
            .......22f222222f22......
            ..........ffffff.........
            ..........ff..ff.........
            `,img`
            .........................
            ..........ffff...........
            ........ffaaaaff.........
            .......faaaffaaaf........
            .......ffffccffff........
            ......ffacaccacaff.......
            ......fafcfffcfcaf.......
            ......fffccaafcfff.......
            ......faafcaaffcaf.......
            ......faaafaaaffaff......
            ......faaaaaaaaaaff......
            ......ffaaaaaaaaf........
            ......f2ffffffffa........
            ......fddacccccf2........
            ......f2aaffffffa........
            .............fff.........
            `],
        100,
        false
        )
    }
    if (direction == 4) {
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            .....ffff...............
            ...fffccfff.............
            ..fffccccfff............
            .fffaaaaaafff...........
            .ffaccccccaaf...........
            .facffffffcaf...........
            .ffffaaaaffff...........
            ffafbf22fbfaff..........
            faa21fddf12aaf..........
            .ffffdddddaaf...........
            f2222f222aaf............
            f4444f22ccf2a...........
            f4444fcc22fd2...........
            .f55f22222f22...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ......ffff..............
            ....fffccfff............
            ...fffccccfff...........
            ..fffaaaaaafff..........
            ..ffaccccccaaf..........
            ..facffffffcaf..........
            ..ffffaaaaffff..........
            .ffafbf22fbfaff.........
            .faa21fddf12aaf.........
            fdfaaddddd2aff..........
            fbffaa222add2a..........
            fbf2fccccadda...........
            fcf.fcccccaa............
            .ff.f22c2c2f............
            ....fff22cff............
            .....f22cff.............
            ....c22c................
            ....c2c.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            .......ff...............
            .....ffccff.............
            ...fffccccfff...........
            ..fffccccccfff..........
            ..fffccccccfff..........
            ..faaaaaaaaaaff.........
            .ffaccccccccaff.........
            .fffffaaaafffff.........
            fdfafbf22fbfaff.........
            fbfa21fddf12af..........
            fbffa2dddd2afa..........
            fcfafcccccf2a...........
            .ff2f22cc2f2a...........
            ....ffffffdda...........
            .....ffffadda...........
            ..........aa............
            .........ccc............
            ........cc2cc...........
            .........c2c............
            .........c2c............
            .........c2c............
            .........c2c............
            `,img`
            ......ffff..............
            ....fffccfff............
            ...fffccccfff...........
            ..fffaaaaaafff..........
            ..ffaccccccaaf..........
            ..facffffffcaf..........
            ..ffffaaaaffff......ccc.
            .ffafbf22fbfaff....c22c.
            .ffafbf22fbfaff...c22c..
            .faa2dddddd2aaf.cc22c...
            fdfaaddddd2aaffac22c....
            fbffaa2222aa2fddccc.....
            fbf2fccccccf1adda.......
            fcf.fccccccf22aa........
            .ff.f22cc22f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile7`, function (sprite, location) {
    mySprite4.follow(mySprite, 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile4`, function (sprite, location) {
    sprites.destroyAllSpritesOfKind(SpriteKind.weapon_book)
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    100,
    false
    )
    tiles.loadMap(tiles.createMap(tilemap`level3`))
    tiles.placeOnTile(mySprite, tiles.getTileLocation(7, 3))
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    flick = 1
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
    direction = 4
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f c f a a a a f f . . . 
        . . . f c c c f a a a a f f . . 
        . . . f a a a a f f a a a f . . 
        . . f a c c c c a a f f f f . . 
        . . f c a f f f f c c c a f . . 
        . . f f f a a a f f f f f f f . 
        . . f a a 2 2 c c a 2 2 a f f . 
        . . f f a d d b 1 2 d 2 a a f . 
        . f d a f d d d d 2 a a a f . . 
        . f b a f a a a 2 a a f . . . . 
        . f b b a d d 2 c c c f . . . . 
        . . f b a d d a 2 2 2 f f . . . 
        . . . f f a a f f f f f f . . . 
        . . . . f f f . . . f f . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f c f a a a a f f . . . 
        . . . f c c c f a a a a f f . . 
        . . . f a a a a f f a a a f . . 
        . . f a c c c c a a f f f f . . 
        . . f c a f f f f c c c a f . . 
        . . f f f a a a f f f f f f f . 
        . . f a a 2 2 c c a 2 2 a f f . 
        . . . f a d d b 1 2 d 2 a a f . 
        . . . . f d d d a a a a a f . . 
        . . . . f a 2 a d d 2 f . . . . 
        . . . . f c c a d d a f . . . . 
        . . . f f c 2 f a a f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . . f f f . . . f f . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f c f a a a a f f . . . 
        . . . f c c c f a a a a f f . . 
        . . . f a a a a f f a a a f . . 
        . . f a c c c c a a f f f f . . 
        . . f c a f f f f c c c a f . . 
        . . f f f a a a f f f f f f f . 
        . . f a a 2 2 c c a 2 2 a f f . 
        . . f f a d d b 1 2 d 2 a a f . 
        . f d d f d d d d 2 a a a f . . 
        . f b b f a a a 2 a a f f . . . 
        . f b b a d d 2 c 2 2 f . . . . 
        . . f b a d d a 2 c 2 a . . . . 
        . . . f f a a f 2 2 c f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f c f a a a a f f . . . . 
        . . f c c c f a a a a f f . . . 
        . . f a a a a f f a a a f . . . 
        . f a c c c c a a f f f f . . . 
        . f c a f f f f c c c a f . . . 
        . f f f a a a f f f f f f f . . 
        . f a a 2 2 c c a 2 2 a f f . . 
        . . f a d d b 1 2 d 2 a a f . . 
        . . . f d d d a a a a a f . . . 
        . . . f a 2 a d d 2 f . . . . . 
        . . . f c c a d d a f . . . . . 
        . . f f c 2 f a a f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile3`, function (sprite, location) {
    tiles.loadMap(tiles.createMap(tilemap`level2`))
    tiles.placeOnTile(mySprite, tiles.getTileLocation(8, 14))
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
    direction = 1
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
    direction = 2
})
controller.combos.attachCombo("A+U", function () {
    mySprite.ay = 50
    if (mySprite.tileKindAt(TileDirection.Center, sprites.dungeon.darkGroundCenter)) {
        mySprite.ay = 0
        game.splash("don't jump inside")
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . f f a a a a f c f . . . . 
        . . f f a a a a f c c c f . . . 
        . . f a a a f f a a a a f . . . 
        . . f f f f a a c c c c a f . . 
        . . f a c c c f f f f a c f . . 
        . f f f f f f f a a a f f f . . 
        . f f a 2 2 a c c 2 2 a a f . . 
        . f a a 2 d 2 1 b d d a f f . . 
        . . f a a a 2 d d d d f a d f . 
        . . . . f a a 2 a a a f a b f . 
        . . . . f c c c 2 d d a b b f . 
        . . . f f 2 2 2 a d d a b f . . 
        . . . f f f f f f a a f f . . . 
        . . . . f f . . . f f f . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . f f a a a a f c f . . . . 
        . . f f a a a a f c c c f . . . 
        . . f a a a f f a a a a f . . . 
        . . f f f f a a c c c c a f . . 
        . . f a c c c f f f f a c f . . 
        . f f f f f f f a a a f f f . . 
        . f f a 2 2 a c c 2 2 a a f . . 
        . f a a 2 d 2 1 b d d a f . . . 
        . . f a a a a a d d d f . . . . 
        . . . . f 2 d d a 2 a f . . . . 
        . . . . f a d d a c c f . . . . 
        . . . f f f a a f 2 c f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . . f f . . . f f f . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . f f a a a a f c f . . . . 
        . . f f a a a a f c c c f . . . 
        . . f a a a f f a a a a f . . . 
        . . f f f f a a c c c c a f . . 
        . . f a c c c f f f f a c f . . 
        . f f f f f f f a a a f f f . . 
        . f f a 2 2 a c c 2 2 a a f . . 
        . f a a 2 d 2 1 b d d a f f . . 
        . . f a a a 2 d d d d f d d f . 
        . . . f f a a 2 a a a f b b f . 
        . . . . f 2 2 c 2 d d a b b f . 
        . . . . a 2 c 2 a d d a b f . . 
        . . . . f c 2 2 f a a f f . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . f f a a a a f c f . . . . 
        . . f f a a a a f c c c f . . . 
        . . f a a a f f a a a a f . . . 
        . . f f f f a a c c c c a f . . 
        . . f a c c c f f f f a c f . . 
        . f f f f f f f a a a f f f . . 
        . f f a 2 2 a c c 2 2 a a f . . 
        . f a a 2 d 2 1 b d d a f . . . 
        . . f a a a a a d d d f . . . . 
        . . . . f 2 d d a 2 a f . . . . 
        . . . . f a d d a c c f . . . . 
        . . . f f f a a f 2 c f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . . f f . . . f f f . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
    direction = 3
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . f f a c f f f f f f c a f f . 
        . f f f f f a a a a f f f f f . 
        . . f a f c c 2 2 c c f a f . . 
        . f f a 2 1 b d d b 1 2 a f . . 
        f a f f a 2 d d d d 2 a f a . . 
        f b f a f c c c c a d d 2 a . . 
        f b f 2 f c c c c a d d a . . . 
        f c f . f 2 2 c c f a a . . . . 
        . f f . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f a a c c c c c c a f f . . 
        . f f a c f f f f f f c a f f . 
        . f f f f f a a a a f f f f f . 
        . . f a f b f 2 2 f b f a f . . 
        . . f a 2 1 f d d f 1 2 a f . . 
        . . a f f f f d d d 2 a f . . . 
        . . f d d d d f c c c f a f . . 
        . . f b b b b f c c c f 2 a . . 
        . . f b b b b f c 2 2 f . . . . 
        . . . f c c f f f f f f . . . . 
        . . . . f f . . . f f f . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f a a c c c c c c a f f . . 
        . f f a c f f f f f f c a f f . 
        . f f f f f a a a a f f f f f . 
        . . f a f c c 2 2 c c f a f . . 
        . . f a 2 1 b d d b 1 2 a f f . 
        . . a f a 2 d d d d 2 a f f a f 
        . . a 2 d d a c c c c f a f b f 
        . . . a d d a c c c c f 2 f b f 
        . . . . a a f c c 2 2 f . f c f 
        . . . . . f f f f f f f . f f . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    true
    )
    mySprite.ay = 0
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile5`, function (sprite, location) {
    tiles.loadMap(tiles.createMap(tilemap`level6`))
    tiles.placeOnTile(mySprite, tiles.getTileLocation(5, 8))
    mySprite4 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd1ff11ff1df......
        ......fddff11ffddf......
        ......fbdffddffdbf......
        ......fcdff11ffdcf......
        .....ffffff11ffbf.......
        ....fc111ffb1fffff......
        ....f1b1bfbfbfc111cf....
        ....fbfbffffff1b1b1f....
        .....2...fffffffbfbf....
        ..........fffff..2......
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(mySprite4, tiles.getTileLocation(8, 18))
    mySprite5 = statusbars.create(20, 4, StatusBarKind.Health)
    mySprite5.attachToSprite(mySprite4)
    mySprite5.setBarBorder(1, 15)
})
scene.onOverlapTile(SpriteKind.Enemy, assets.tile`transparency16`, function (sprite, location) {
    mySprite4.destroy()
})
controller.combos.attachCombo("A+B", function () {
    mySprite.sayText("" + mySprite3 + " attack", 5000, true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (direction == 1) {
        otherSprite.destroy()
    } else if (direction == 2) {
        otherSprite.destroy()
    } else if (direction == 3) {
        otherSprite.destroy()
    } else if (direction == 4) {
        otherSprite.destroy()
    }
    mySprite6 = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...........fffffff..............
        ...........fffffff..............
        ........fff1111111fff...........
        .......fbb111111111bbff.........
        .......fbb111111111bbff.........
        .......f1111111111111ff.........
        ......fd1111111111111ddf........
        ......fd11fff111fff11ddf........
        ......fd11fff111fff11ddf........
        ......fdddfff111fffddddf........
        ......fbddfffdddfffddbbf........
        ......fcddfff111fffddccf........
        ......fcddfff111fffddccf........
        ....fffffffff111fffbbff.........
        ..ffcc1111fffbb1ffffffff........
        ..ff11b1bbfbbffbffc11111ccf.....
        ..ff11b1bbfbbffbffc11111ccf.....
        ..ffbbfbffffffffff1bb11b11f.....
        ....22....fffffffffffbbfbbf.....
        ...........ffffffff....2........
        ...........ffffffff....2........
        .............fffff..............
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.Player)
    mySprite6.setScale(5, ScaleAnchor.Middle)
    tiles.loadMap(tiles.createMap(tilemap`level9`))
    tiles.placeOnRandomTile(mySprite6, assets.tile`myTile10`)
    scene.cameraFollowSprite(mySprite6)
    mySprite.setFlag(SpriteFlag.Invisible, true)
    statusbar2.setFlag(SpriteFlag.Invisible, true)
    statusbar.setFlag(SpriteFlag.Invisible, true)
    color.setPalette(
    color.originalPalette
    )
    flick = 0
    stoopppre = 1
})
let stoopppre = 0
let mySprite6: Sprite = null
let mySprite5: StatusBarSprite = null
let flick = 0
let mySprite4: Sprite = null
let direction = 0
let mySprite2: Sprite = null
let mySprite3 = 0
let statusbar2: StatusBarSprite = null
let statusbar: StatusBarSprite = null
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    ..........22..............................................22....................................................................................................
    .......222.22..........................................22222....................................................................................................
    ......22....222......................................222...2...2......22........................................................................................
    .....22.......22..................................222..2222...22..2222.22..............2........................................................................
    ......22.......2..................2222...........222..........222222.2...222..........2222......................................................................
    .......2.......22................2.22222.........22...............2.2......2222222....22.2...........22..........................................222............
    .......2........2.2.............22....222........22.................2..................2.2..........222......2........2.........................222222..........
    .......2........222.............2....22.........222222.............2..................2..22.........222......2..22...22.........22...........2222.222....2222...
    .......22.......22.............2222.2.2..........22222222.222...222...................22..2........2..22.....2.222222222.......222.......2....222.2.22222222222.
    .......2.......22.............22222.222..........22...2222..2...2......................2..22......22...2....222222222..2...2...2.2......22....2..22.........222.
    ......22.....22...............22.....22.................22..2....2222..2..............22...2.....22....2....22.........2222....2.2......22....2...22222.........
    ......2.....22................2.......22................22222.......2.22...22..222....2....22....2.....2....22.................2.2.......2............2.........
    ......2222222...............222.......22..................22.......222.2222.2222......22....2....2.....2.....22................2.22......2...........22.........
    ......222...2...............222.......22..................222.....22..................22....2....2.....2......2................2..22.....2..........2...........
    ......2.22222...............22...2...22...................222.....2...................22....2....222...2......22222............22..2.....2.........22...........
    .....2.....22..............222222222222222222..............22......2...................2....2.....2...22.....2.2..2..22...2......2222...2...........22..........
    ....222....22..222......222222222...22222..................22......2..................2.....2.....2...22.....222...22222.22......22.22..2............22.........
    ......22....2222.........22.222222..22.2222................22.....2...................22....22....2....2......2....2...22.......2....2..2............22.........
    ......22......2222.......2222.......2..2..2..........2222.22......2............22......22....2....2....2......2................22.....2.22...........2..........
    ......2..........2......2222........2..2.2..........22..2222.....2.............22.....22.....22..22....2......2.................2.....22.22........22...........
    ......22........2.......2.2............2222.........2..22.......2.2222.222222222.....22.......22.2.....2......2..................2.....2.22........2............
    .......2........2.......222.............2.2.........2.22.......222...22...............2........222.....2......2.................22.....2.2.........222..........
    ......2........2.......2.2..............2.2.......2.22.........2.....22..............22.........2......22....22..22222222......22.......22...........2..........
    .....22........22......222..............2.22......222...............2................2..................2....22222...22.22.2....22......22...........2..........
    .....222.......2.......22...............2222......2222.............22.2........................................2.....2...222...22.......22...........2..........
    .......2......2........222...............22222....2222.............2222.................................................................2............2..........
    .......2.....2.........2....................2.22.....................................................................................................2..........
    .......2.22.22..............................222.................................................................................................................
    .......22222................................22..................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    .................................................22.............................................................................................................
    ......................................2...........2.......................................22....................................................................
    .....................................22..........2...................2222222............22222222................................................................
    ......................................22........2....................2......22222.....22......22................................................................
    .......................................2.......222...................2.........22.....2........2........22......................................................
    .......................................2.........22..........2.......2..........2.....22.......2.......222...........22.........................................
    ......................................22..........2.......2222.......2..........2.....22.......2......22..2.........222.........................................
    ......................................2.......2...2.....22..2........2................2........2.....2.2...2.......22..22222....................................
    ....................................2222222222222222....2....2.....22................22........2....2.......2.....22.......2....................................
    .....................................2..........22......2.....2...22.................2..............2.......22....2........2....................................
    .....................................2..........2222....2.....2...2..................2..............2........22...2.......22....................................
    .....................................2222..........2.....2....2...22.................2..............22.......22..22.............................................
    ........................................22.........2.....22..2.....2.................22.............2........2...2..............................................
    ........................................2.........2........22......2..................2.............2.......22...2..............................................
    .......................................2..........2.2..............22..................2............22..22222....2..............................................
    .......................................2.........2222..................................2.............222.........2..............................................
    .....................................22............2.............................................................2..............................................
    ......................................2...........22.............................................................2..............................................
    ......................................2.........22..............................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    `)
game.splash("press a to start")
if (controller.A.isPressed()) {
    storyboard.loaderBootSequence.register()
    storyboard.pop()
    storyboard.replace("")
    storyboard.push("")
    storyboard.start("")
    scene.setBackgroundImage(img`
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        `)
    mySprite = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f c c f f f . . . . 
        . . . f f f c c c c f f f . . . 
        . . f f f a a a a a a f f f . . 
        . . f f a c c c c c c a a f . . 
        . . f a c f f f f f f c a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b c 2 2 c b f a f f . 
        . f a a 2 1 b d d b 1 2 a a f . 
        . . f f f f d d d d d a a f . . 
        . f a b b a f 2 2 2 a a f . . . 
        . f b a a b f c c 2 c f 2 a . . 
        . f c b b c f 2 2 c c f d 2 . . 
        . . f c c f 2 c c 2 2 f 2 2 . . 
        . . . f f f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    statusbar = statusbars.create(20, 4, StatusBarKind.Health)
    statusbar2 = statusbars.create(20, 4, StatusBarKind.Energy)
    statusbar2.value = 0
    statusbar2.positionDirection(CollisionDirection.Bottom)
    statusbar2.setBarBorder(1, 10)
    statusbar.value = 100
    statusbar2.setBarSize(20, 4)
    statusbar.attachToSprite(mySprite)
    statusbar2.attachToSprite(mySprite, 0, 0)
    statusbar.setBarBorder(1, 15)
    statusbar.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
    statusbar.setLabel("HP")
    statusbar2.setLabel("energy")
    mySprite3 = 20
    mySprite2 = sprites.create(img`
        .cccccccccccccccccccccc.
        cbddddddddddddddddddddbc
        cddddddddddddddddddddddc
        cddddddddddddddddddddddc
        cddddddddddddddddddddddc
        cddddddddddddddddddddddc
        cddddddddddddddddddddddc
        cbddddddddddddddddddddbc
        ccbbbbbbbbbbbbbbbbbbbbcc
        ccffffffffffffffffffffcc
        cbcc33c6c44c3c7c66c3ccbc
        cbcc33c6c44c3c7c66c3ccbc
        fbcc33c6c44ccc7c66c3ccbf
        fdccccccc44cccccccccccdf
        fdcbbdddd44ddddddddbbcdf
        fdffffffffffffffffffffdf
        fdccc6c33c4c6c44c3c7ccdf
        fdccc6c33c4c6c44c3c7ccdf
        fdccc6c33ccc6c44ccc7ccdf
        fdccccccccccccccccccccdf
        fdcbbddddddddddddddbbcdf
        fdcbbddddddddddddddbbcdf
        fdffffffffffffffffffffdf
        ffffffffffffffffffffffff
        `, SpriteKind.weapon_book)
    tiles.setCurrentTilemap(tilemap`level1`)
    scene.cameraFollowSprite(mySprite)
    tiles.placeOnTile(mySprite2, tiles.getTileLocation(8, 0))
    controller.moveSprite(mySprite)
}
game.onUpdateInterval(5000, function () {
	
})
game.onUpdateInterval(500, function () {
    if (stoopppre == 1) {
        mySprite6.destroy()
        color.startFade(color.Black, color.originalPalette, 500)
        mySprite.setFlag(SpriteFlag.Invisible, false)
        statusbar2.setFlag(SpriteFlag.Invisible, false)
        statusbar.setFlag(SpriteFlag.Invisible, false)
        stoopppre = 0
        tiles.loadMap(tiles.createMap(tilemap`level10`))
        mySprite.sayText("Did I just pass out?", 2000, true)
        tiles.placeOnRandomTile(mySprite, sprites.dungeon.darkGroundCenter)
        scene.cameraFollowSprite(mySprite)
    }
})
game.onUpdateInterval(100, function () {
    if (flick == 1) {
        color.setPalette(
        color.Black
        )
        flick = 2
    } else if (flick == 2) {
        color.setPalette(
        color.originalPalette
        )
        flick = 1
    }
})
